name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/jdrozdnovak/ha_pagerduty/v$RESOLVED_VERSION/total.svg)](https://github.com/jdrozdnovak/ha_pagerduty/releases/v$RESOLVED_VERSION)
  ## Changes

  $CHANGES
