name: Automated Release Workflow (dev)

on:
  pull_request:
    branches:
        - dev

permissions:
  contents: write

jobs:
  alfa-release:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
    
      - name: Bump version and push tag (Alfa)
        id: bump_alfa_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PRERELEASE: true
            WITH_V: true
            DEFAULT_BUMP: "patch"
            PRERELEASE_SUFFIX: alfa.${{ github.run_number }}
    
      - name: Create or Overwrite Alfa Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.bump_alfa_version.outputs.new_tag }}
            name: Alfa Release - ${{ steps.bump_alfa_version.outputs.new_tag }}
            allowUpdates: true
            prerelease: true

  test-sh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test SH
        run: |
          cd ${{ github.workspace }}
          ls -la
          pwd

  purge-alfa-releases:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Purge Alfa Releases
        run: bash ./purge.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MERGED_BRANCH: ${{ github.event.pull_request.head.ref }}
            GITHUB_REPOSITORY: ${{ github.repository }}
