name: Automated Release Workflow

on:
  push:
    branches:
        - 'dev'
    paths:
      - 'custom_components/**'
  pull_request:
    types:
        - closed
    branches:
        - main

permissions:
  contents: write

jobs:
  beta-release:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
            fetch-depth: '0'

      - name: Compute next version (Beta)
        id: bump_beta_version
        uses: anothrNick/github-tag-action@1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PRERELEASE: true
            WITH_V: true
            DEFAULT_BUMP: "patch"
            PRERELEASE_SUFFIX: beta.${{ github.run_number }}
            DRY_RUN: true

      - name: Stamp version into manifest and tag
        env:
            VERSION_TAG: ${{ steps.bump_beta_version.outputs.new_tag }}
        run: |
            jq --arg version "$VERSION_TAG" '.version = $version' custom_components/pagerduty/manifest.json > temp.json
            mv temp.json custom_components/pagerduty/manifest.json
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "Release $VERSION_TAG"
            git tag -a "$VERSION_TAG" -m "Release $VERSION_TAG"
            git push origin "refs/tags/$VERSION_TAG"

      - name: Create or Overwrite Beta Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.bump_beta_version.outputs.new_tag }}
            name: Beta Release - ${{ steps.bump_beta_version.outputs.new_tag }}
            allowUpdates: true
            prerelease: true

  purge-beta-releases:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Purge Beta Releases
        run: bash ./purge.sh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MERGED_BRANCH: ${{ github.event.pull_request.head.ref }}
            GITHUB_REPOSITORY: ${{ github.repository }}


  latest-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
            ref: ${{ github.event.pull_request.merge_commit_sha }}
            fetch-depth: '0'

      - name: Compute next version (Latest)
        id: bump_latest_version
        uses: anothrNick/github-tag-action@1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: "minor"
            DRY_RUN: true

      - name: Stamp version into manifest and tag
        env:
            VERSION_TAG: ${{ steps.bump_latest_version.outputs.new_tag }}
        run: |
            jq --arg version "$VERSION_TAG" '.version = $version' custom_components/pagerduty/manifest.json > temp.json
            mv temp.json custom_components/pagerduty/manifest.json
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "Release $VERSION_TAG"
            git tag -a "$VERSION_TAG" -m "Release $VERSION_TAG"
            git push origin "refs/tags/$VERSION_TAG"

      - name: Create Latest Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.bump_latest_version.outputs.new_tag }}
            name: "Release ${{ steps.bump_latest_version.outputs.new_tag }}"
            body: ${{ github.event.pull_request.body }}
            draft: false
            prerelease: false
